### ISSUE TITLE
Xsnip is blurry so I can't see what I'm snipping

### ISSUE THREAD

**Issue by jtbx** [ws-kj/xsnip#2] opened 2021-12-29 04:51 UTC
It's blurry when I start xsnip, so I can't see what I'm snipping. Even when I draw the square, it's still blurry inside.

**Comment by ws-kj** [comment] 2021-12-29 04:52
Hi, I'm very sorry to hear that. Could you please tell me what WM/DE you're running, as well as the specs of your monitor? Thanks.

**Comment by jtbx** [comment] 2021-12-29 07:36
I'm running DWM (my config's @ jtbx/dwm), & my monitor is my laptop's built in display, 1920x1080 @ 60hz.

**Comment by ws-kj** [comment] 2021-12-29 16:36
Thanks, when I have a few hours I will set up your environment and see if I can figure out what's going on.

**Comment by danrobi11** [comment] 2021-12-29 17:27
Same here. Selecting = black screen and the screenshot also = black screenshot. 

Distro: MXLinux 21
WM: [EXWM](https://github.com/ch11ng/exwm)

**Comment by jtbx** [comment] 2021-12-29 23:45
I suspected it could have been my picom config (I have blur enabled), so I excluded xsnip in the blur configuration, and it hasn't changed. @danrobi11 have you got picom / a blur compositor enabled?

**Comment by danrobi11** [comment] 2021-12-30 06:24
@jtbx I dont think I do

whereis picom
picom:

**Comment by jtbx** [comment] 2021-12-30 20:31
Picom is a compositor. It allows for shadows, rounded corners, and blurring on windows. If you don't have picom, that means it's not an issue with picom.

**Comment by dakata1337** [comment] 2022-01-05 14:41
@danrobi11 
From https://stackoverflow.com/questions/23051594/how-to-set-xlib-window-background-transparent.
> make sure you are running composite manager that can handle transparency correctly

Installing picom with the default config fixes it.

**Comment by ws-kj** [comment] 2022-01-05 17:42
Hello- sorry for the delayed response to this, I've been busy with family over the holidays. It seems like the transparent window doesn't play nice with various compositors, so I'm going to create a config option that will fill the overlay with a temporary fullscreen screenshot which should have the same effect as a transparent overlay, although performance will take a small hit.

**Comment by ws-kj** [comment] 2022-01-07 20:40
@jtbx I've added option in `config.h` to compile in opaque mode, which does not rely on compositor transparency. It should fix the issue that you're having. Let me know if it works so I can close this issue.

**Comment by ws-kj** [comment] 2022-01-08 16:31
I'm confident that opaque mode fixes this issue.

**Closed as completed by ws-kj** 2022-01-08 16:31 UTC

**Comment by danrobi11** [comment] 2022-01-08 23:21
> I'm confident that opaque mode fixes this issue.

Yes its working as intended with `-o`. Thank you much for the support, very much appreciated.

**Comment by ws-kj** [comment] 2022-01-08 23:53
Glad to hear it!
